/*
 * Article
 *
 * This is a simple API Server based DDD
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/",
		Index,
	},

	Route{
		"AddArticle",
		strings.ToUpper("Post"),
		"/article",
		AddArticle,
	},

	Route{
		"DeleteArticle",
		strings.ToUpper("Delete"),
		"/article/{id}",
		DeleteArticle,
	},

	Route{
		"GetArticle",
		strings.ToUpper("Get"),
		"/article/{id}",
		GetArticle,
	},

	Route{
		"GetArticles",
		strings.ToUpper("Get"),
		"/article",
		GetArticles,
	},

	Route{
		"UpdateArticle",
		strings.ToUpper("Put"),
		"/article/{id}",
		UpdateArticle,
	},

	Route{
		"CreateUser",
		strings.ToUpper("Post"),
		"/user",
		CreateUser,
	},

	Route{
		"DeleteUser",
		strings.ToUpper("Delete"),
		"/user/{username}",
		DeleteUser,
	},

	Route{
		"GetUserByName",
		strings.ToUpper("Get"),
		"/user/{username}",
		GetUserByName,
	},

	Route{
		"GetUsers",
		strings.ToUpper("Get"),
		"/user",
		GetUsers,
	},

	Route{
		"LoginUser",
		strings.ToUpper("Get"),
		"/user/login",
		LoginUser,
	},

	Route{
		"LogoutUser",
		strings.ToUpper("Get"),
		"/user/logout",
		LogoutUser,
	},

	Route{
		"UpdateUser",
		strings.ToUpper("Put"),
		"/user/{username}",
		UpdateUser,
	},
}
